nombre = 'Cesar Quintero'
print ('Uso del operador in:')
print ('e' in nombre)
print ('w' in nombre)
print()
print ('Uso de la función "Len":')
print(len(nombre))
print()
print('Uso del método "upper":')
print(nombre.upper())
print('Uso del método "lower":')
print(nombre.lower())
print('Uso del método "title":')
print(nombre.title())
print('Uso del método "count":')
print(nombre.count('Q'))

